ARG python_version=3.10
ARG alpine_version=3.15
ARG poetry_version=1.1.13
FROM python:${python_version}-alpine${alpine_version}

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.1.13


RUN set -ex \
    && apk add --no-cache build-base postgresql-dev openssl-dev libffi-dev rust \
    && pip install --upgrade pip \
    && pip install "poetry==$POETRY_VERSION"

