ARG python_version=3.10
ARG alpine_version=3.15
ARG poetry_version=1.1.13

FROM python:${python_version}-alpine${alpine_version}

ARG poetry_version=1.1.13

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  POETRY_VERSION=$poetry_version

RUN apk add --no-cache \
    curl build-base postgresql-dev openssl-dev libffi-dev rust \
    && pip install --upgrade pip \
    && curl -sSL https://install.python-poetry.org | python3 - --version=$POETRY_VERSION

