name: build

on:
  push:
    branches:
    - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
        - 3.9.12
        - 3.10.4
        debian_version:
        - bullseye
        poetry_version:
        - 1.1.14
        - 1.2.0b3
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Alpine
      uses: docker/build-push-action@v2
      with:
        platforms: "linux/amd64,linux/arm64"
        push: true
        tags: isaacp/poetrypg:${{ matrix.poetry_version }}-py${{ matrix.python_version }}-alpine
        file: Dockerfile.alpine
        build-args: |
          BUILDKIT_MULTI_PLATFORM=1
          python_version=${{ matrix.python_version }}
          poetry_version=${{ matrix.poetry_version }}
    - name: Build and push Debian
      uses: docker/build-push-action@v2
      with:
        platforms: "linux/amd64,linux/arm64"
        push: true
        tags: isaacp/poetrypg:${{ matrix.poetry_version }}-py${{ matrix.python_version }}-${{ matrix.debian_version }}
        file: Dockerfile.debian
        build-args: |
          BUILDKIT_MULTI_PLATFORM=1
          python_version=${{ matrix.python_version }}
          poetry_version=${{ matrix.poetry_version }}
          os_variant=${{ matrix.debian_version }}
