name: bump

on:
  schedule:
    # At minute 13 past every 12th hour. https://crontab.guru/#13_*/12_*_*_*
  - cron: "13 */12 * * *"
  push:
    branches:
    - 'main'

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - name: Run Version Check
        run: |
          git config --global user.email "parrotmac+repo-bot@gmail.com"
          git config --global user.name "Isaac Parker"
          git config --get-regexp "user.*"
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$PATH:$HOME/.local/bin"
          poetry install
          poetry run python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
