name: bump

on:
  schedule:
    # Every 15 minutes
  - cron: "*/15 * * * *"
  push:
    branches:
    - 'main'

jobs:
  check_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Run Version Check
        run: |
          python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}